# Generated by Django 5.0.2 on 2024-02-10 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patinete',
            name='coste_final',
        ),
        migrations.RemoveField(
            model_name='patinete',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='patinete',
            name='fecha_desbloqueo',
        ),
        migrations.RemoveField(
            model_name='patinete',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='patinete',
            name='usuario',
        ),
        migrations.AddField(
            model_name='patinete',
            name='estado_alquiler',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desbloqueo', models.DateField(null=True)),
                ('fecha_entrega', models.DateField(null=True)),
                ('coste_final', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('patinete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patines.patinete')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Alquileres',
                'ordering': ['fecha_entrega'],
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
