# Generated by Django 5.0.2 on 2024-02-10 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='patinete',
            old_name='estado',
            new_name='estado_alquiler',
        ),
        migrations.RemoveField(
            model_name='patinete',
            name='coste_final',
        ),
        migrations.RemoveField(
            model_name='patinete',
            name='fecha_desbloqueo',
        ),
        migrations.RemoveField(
            model_name='patinete',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='patinete',
            name='usuario',
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('fecha_desbloqueo', models.DateField()),
                ('fecha_entrega', models.DateField()),
                ('coste_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('patine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patines.patinete')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
