# Generated by Django 5.0.2 on 2024-02-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patines', '0002_rename_estado_patinete_estado_alquiler_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alquiler',
            options={'ordering': ['fecha_entrega'], 'verbose_name_plural': 'Alquileres'},
        ),
        migrations.RemoveField(
            model_name='patinete',
            name='estado_alquiler',
        ),
    ]
