# Generated by Django 5.0.2 on 2024-02-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patines', '0002_remove_patinete_coste_final_remove_patinete_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='fecha_desbloqueo',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='fecha_entrega',
            field=models.DateTimeField(null=True),
        ),
    ]
